[workspace]
members = ["miden-lib", "miden-tx", "mock", "objects"]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true

[profile.test-release]
inherits = "release"
debug = true
debug-assertions = true
overflow-checks = true

[profile.bench]
codegen-units = 1
lto = true

[workspace.dependencies]
assembly = { package = "miden-assembly", git = "https://github.com/0xPolygonMiden/miden-vm", branch = "andrew-duplicate-proc-fix", default-features = false }
miden-verifier = { package = "miden-verifier", git = "https://github.com/0xPolygonMiden/miden-vm", branch = "andrew-duplicate-proc-fix", default-features = false }
vm-processor = { package = "miden-processor", git = "https://github.com/0xPolygonMiden/miden-vm", branch = "andrew-duplicate-proc-fix", default-features = false }
