[package]
name = "miden-objects"
version = "0.1.0"
description = "Core components of the Miden rollup"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-base"
categories = ["no-std"]
keywords = []
edition = "2021"
rust-version = "1.75"

[[bench]]
name = "account_seed"
harness = false

[lib]
bench = false

[features]
default = ["std"]
concurrent = ["std"]
serde = ["dep:serde", "miden-crypto/serde"]
std = ["assembly/std", "miden-crypto/std", "miden-verifier/std", "vm-core/std", "vm-processor/std"]
testing = []

[dependencies]
assembly = { workspace = true }
log = { version = "0.4", optional = true }
miden-crypto = { version = "0.8", default-features = false }
miden-verifier = { workspace = true }
serde = { version = "1.0", optional = true, default-features = false, features = ["derive"] }
vm-core = { package = "miden-core", git = "https://github.com/0xPolygonMiden/miden-vm", branch = "andrew-duplicate-proc-fix", default-features = false }
vm-processor = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", default-features = false, features = [
    "html_reports",
] }
tempfile = { version = "3.0" }
